### ISSUE TITLE
Erro no Tahiti após o processo de instalação.

### ISSUE THREAD

**Issue by rommeldias** [eubr-bigsea/docker-lemonade#22]
Boa noite,

Em uma máquina com o Ubuntu 20.04, realizei a instalação do Lemonade (versão atual do github) via docker-compose seguindo os passos descritos. Após o build, ocorreu falha na tentativa de acesso à plataforma no localhost:23456 (Error: Request failed with status code 404).

Realizando uma inspeção nos logs de cada módulo do Lemonade, o Tahiti reportou o seguinte:

> **/usr/local/tahiti
DB migration: successful
Tahiti server started, logging to /usr/local/tahiti/logs/tahiti-server--2663301cb620.out (pid=10)
Error in monkey patch
Traceback (most recent call last):
  File "/usr/local/tahiti/tahiti/runner/tahiti_server.py", line 12, in <module>
    import eventlet.wsgi
  File "/usr/local/lib/python3.7/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/usr/local/lib/python3.7/site-packages/eventlet/convenience.py", line 4, in <module>
    from eventlet import greenpool
  File "/usr/local/lib/python3.7/site-packages/eventlet/greenpool.py", line 4, in <module>
    from eventlet import queue
  File "/usr/local/lib/python3.7/site-packages/eventlet/queue.py", line 49, in <module>
    from eventlet.event import Event
  File "/usr/local/lib/python3.7/site-packages/eventlet/event.py", line 3, in <module>
    from eventlet import hubs
  File "/usr/local/lib/python3.7/site-packages/eventlet/hubs/__init__.py", line 7, in <module>
    from eventlet.support import greenlets as greenlet
  File "/usr/local/lib/python3.7/site-packages/eventlet/support/__init__.py", line 6, in <module>
    from eventlet.support import greenlets
  File "/usr/local/lib/python3.7/site-packages/eventlet/support/greenlets.py", line 3, in <module>
    import greenlet
  File "/usr/local/lib/python3.7/site-packages/greenlet/__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ImportError: Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/lib/python3.7/site-packages/greenlet/_greenlet.cpython-37m-x86_64-linux-gnu.so)**

Como poderíamos solucionar esse erro?
Obrigado.

**Comment by waltersf** [comment]
Atualizamos a imagem usada pelo container do Tahiti e aparentemente, resolveu o problema.

Relacionado ao bug https://github.com/eubr-bigsea/tahiti/pull/146

**Comment by rommeldias** [comment]
> Atualizamos a imagem usada pelo container do Tahiti e aparentemente, resolveu o problema.
> 
> Relacionado ao bug [eubr-bigsea/tahiti#146](https://github.com/eubr-bigsea/tahiti/pull/146)

Obrigado pelo rápido retorno, Walter.

O Tahiti foi inicializado sem erros. No entanto, após tentativa de acessar a plataforma, a página carrega até aparecer o erro Request failed with status code 404.

Fazendo uma inspeção nos logs dos containers, o mysql reportou o seguinte:

**2022-12-16T13:58:50.942917Z 2 [Note] Aborted connection 2 to db: 'tahiti' user: 'root' host: '172.26.0.9' (Got an error reading communication packets)**

O log completo do mysql segue abaixo:

 Executing task: docker logs --tail 1000 -f 48bcdb00134462dcc7ad0023851f1880cb5af13825be217dffa7db80d4ba2e59 

2022-12-16 13:58:39+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.40-1.el7 started.
2022-12-16 13:58:39+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2022-12-16 13:58:39+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.40-1.el7 started.
'/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
2022-12-16T13:58:39.934653Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2022-12-16T13:58:39.935392Z 0 [Note] mysqld (mysqld 5.7.40) starting as process 1 ...
2022-12-16T13:58:39.937257Z 0 [Note] InnoDB: PUNCH HOLE support available
2022-12-16T13:58:39.937267Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2022-12-16T13:58:39.937268Z 0 [Note] InnoDB: Uses event mutexes
2022-12-16T13:58:39.937271Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2022-12-16T13:58:39.937272Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.12
2022-12-16T13:58:39.937273Z 0 [Note] InnoDB: Using Linux native AIO
2022-12-16T13:58:39.937538Z 0 [Note] InnoDB: Number of pools: 1
2022-12-16T13:58:39.937623Z 0 [Note] InnoDB: Using CPU crc32 instructions
2022-12-16T13:58:39.938535Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2022-12-16T13:58:39.942582Z 0 [Note] InnoDB: Completed initialization of buffer pool
2022-12-16T13:58:39.943901Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2022-12-16T13:58:39.954769Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2022-12-16T13:58:39.967529Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-12-16T13:58:39.967561Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-12-16T13:58:39.982568Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2022-12-16T13:58:39.983144Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2022-12-16T13:58:39.983149Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2022-12-16T13:58:39.983463Z 0 [Note] InnoDB: Waiting for purge to start
2022-12-16T13:58:40.033612Z 0 [Note] InnoDB: 5.7.40 started; log sequence number 16649650
2022-12-16T13:58:40.033806Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2022-12-16T13:58:40.033910Z 0 [Note] Plugin 'FEDERATED' is disabled.
2022-12-16T13:58:40.035834Z 0 [Note] InnoDB: Buffer pool(s) load completed at 221216 13:58:40
2022-12-16T13:58:40.038628Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
2022-12-16T13:58:40.038638Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
2022-12-16T13:58:40.038641Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
2022-12-16T13:58:40.038642Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
2022-12-16T13:58:40.039164Z 0 [Warning] CA certificate ca.pem is self signed.
2022-12-16T13:58:40.039197Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
2022-12-16T13:58:40.039439Z 0 [Note] Server hostname (bind-address): '0.0.0.0'; port: 3306
2022-12-16T13:58:40.039462Z 0 [Note]   - '0.0.0.0' resolves to '0.0.0.0';
2022-12-16T13:58:40.039480Z 0 [Note] Server socket created on IP: '0.0.0.0'.
2022-12-16T13:58:40.040839Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2022-12-16T13:58:40.049691Z 0 [Note] Event Scheduler: Loaded 0 events
2022-12-16T13:58:40.049915Z 0 [Note] mysqld: ready for connections.
Version: '5.7.40'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
2022-12-16T13:58:50.942917Z 2 [Note] Aborted connection 2 to db: 'tahiti' user: 'root' host: '172.26.0.9' (Got an error reading communication packets)

**Comment by waltersf** [comment]
Reinicia o container citrus, pois pode ser que o Nginx não tenha achado o Tahiti quando este subiu.

**Comment by rommeldias** [comment]
Opa, Walter. Fiz o que sugeriu. Os erros reportados nos logs foram:

citrus_1        | 2022/12/16 15:06:56 [error] 8#8: *1 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.27.0.1, server: , request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", upstream: "http://172.27.0.8:23400/public/configurations/OPENID_CONFIG", host: "localhost:23456", referrer: "http://localhost:23456/"

citrus_1        | 2022/12/16 15:06:56 [error] 8#8: *1 open() "/app/50x.html" failed (2: No such file or directory), client: 172.27.0.1, server: , request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", upstream: "http://172.27.0.8:23400/public/configurations/OPENID_CONFIG", host: "localhost:23456", referrer: "http://localhost:23456/"

**Comment by waltersf** [comment]
Ao executar `docker-compose ps`, todos os serviços estão up? Se algum não estiver, inicie-o e reinicie o serviço citrus.

**Comment by rommeldias** [comment]
Oi, Walter. Estão sim. Para me certificar que está tudo ok, refiz o processo de instalação. No entanto, os erros acima persistiram.

Em algumas vezes, a tela de login não aparece (a tela fica em carregamento). Em outras, aparece, mas mesmo colocando login/senha, não se entra na plataforma.
